CC = g++
CCFLAG = -std=c++11 -Wall -g

countstairs: countstairs.cpp
	$(CC) $(CCFLAG) -o countstairs.exe countstairs.cpp

howsum: howsum.cpp
	$(CC) $(CCFLAG) -o howsum.exe howsum.cpp

clean:
	rm *.exe
	rm -rf *.dSYM
